### ISSUE TITLE
Is this the actual templating system?

### ISSUE THREAD

**Issue by developer239** [neomjs/neomjs-realworld-example-app#2]
Is this the actual way how to write HTML and css in neomjs? Why would anyone think this is a good idea? What is wrong with HTML?

![image](https://user-images.githubusercontent.com/14946081/130324126-7318864b-522f-4bb3-9d00-915131646f26.png)

**Comment by tobiu** [comment]
Hi @developer239,

Actually it is not the way how you would work with neo.

The problem is, that the official requirements on how to create the app are super strict.

We have to use Bootstrap and we have to match a given DOM markup by 100%.

Sadly, this prevents us from using all the higher level widgets like TabContainer, List, Toolbar, Button etc.

On top of this, the app is pretty old. ViewModels were not available at this point.

For more recent examples, I recommend to dive into the calendar or covid apps:

https://github.com/neomjs/neo/tree/dev/src/calendar

https://github.com/neomjs/neo/tree/dev/apps/covid

Best regards,
Tobias

**Comment by developer239** [comment]
@tobiu Thank you for taking your time to react to my passive-aggressive screenshot.  😀 I will take a look at the examples that you linked. The framework looked really good but I am not sure if it ever gets popular without a proper templating system. It reminds me of Elm and the way Elm works with HTML is just terrible. 🙉
