### ISSUE TITLE
Failed to load 'buildScripts/webpack/webpack.server.config.js' config

### ISSUE THREAD

**Issue by corysimmons** [neomjs/neomjs-realworld-example-app#4]
When I try to `npm run server-start`

**Comment by tobiu** [comment]
Hi @corysimmons!

Which version of neo.mjs are you using? I have not updated this repo in quite a while (could do it though). Double-checking if the file: https://github.com/neomjs/neo/blob/dev/buildScripts/webpack/webpack.server.config.mjs exists inside of your version would help.

We still have a version of the RealWorld app inside the neo repo itself:
https://github.com/neomjs/neo/tree/dev/apps/realworld

For the mean time, you could clone / fork the neo repo and get it running locally this way. The dist/prod env will be a bit more heavy-weight here, since neo creates split-chunks across apps & examples.

**Comment by corysimmons** [comment]
>Which version of neo.mjs are you using?

I just ran `npm i`

**Comment by tobiu** [comment]
my guess is that `npm i` will grab the last released version of v3 (we are already at v4.0.66). you can double-check it either inside your package-lock.json or open `node_modules/neo.mjs/package.json`.

**Comment by tobiu** [comment]
ah, i see the problem now. the server config file name got changed from `.js` to `.mjs`.

already updating this repo, stay tuned.

**Comment by tobiu** [comment]
done. pull, npm i, build-all and you should be good.

**Comment by corysimmons** [comment]
Awesome thank you!

**Comment by tobiu** [comment]
you are welcome. hint: joining the slack channel can speed up things a lot:
https://join.slack.com/t/neomjs/shared_invite/zt-6c50ueeu-3E1~M4T9xkNnb~M_prEEOA

plus we just started with doing 2 weekly neo workshops.
